package com.itheima.im61.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.itheima.im61.dao.Contact;
import com.itheima.im61.dao.Sms;

import com.itheima.im61.dao.ContactDao;
import com.itheima.im61.dao.SmsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactDaoConfig;
    private final DaoConfig smsDaoConfig;

    private final ContactDao contactDao;
    private final SmsDao smsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        smsDaoConfig = daoConfigMap.get(SmsDao.class).clone();
        smsDaoConfig.initIdentityScope(type);

        contactDao = new ContactDao(contactDaoConfig, this);
        smsDao = new SmsDao(smsDaoConfig, this);

        registerDao(Contact.class, contactDao);
        registerDao(Sms.class, smsDao);
    }
    
    public void clear() {
        contactDaoConfig.getIdentityScope().clear();
        smsDaoConfig.getIdentityScope().clear();
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public SmsDao getSmsDao() {
        return smsDao;
    }

}
